services:
  questionarios:
    build: .
    container_name: psitest-questionarios
    command: fastapi run app --host 0.0.0.0 --port 80
    ports:
      - 8004:80
    networks:
      - psitest
networks:
  psitest:
    external: true
