services:
  questionarios:
    build: .
    container_name: psitest-questionarios
    command: fastapi dev app --host 0.0.0.0 --port 80
    ports:
      - 8004:80
    volumes:
      - .:/app
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true
